version: '3.8'
services:
    prytaneum-client:
        build:
            context: .
            dockerfile: Dockerfile
            target: BASE_IMAGE
        command: 'yarn start'
        volumes:
            - .:/usr/app
        ports:
            - '3000:3000'
        tty: true
        # stdin_open: true
